version: "3"

services:
  web:
    build: .
    image: sj2d/watch-tower-1
    ports:
      - "5000:5000"
    environment:
      - mongoURI=mongodb+srv://admin2:Nco3GL2vs7GP6FgK@cluster0-9l8kx.mongodb.net/test?retryWrites=true&w=majority
      - secretOrKey=secretSHHHHHHHHHHHHHHHHHHHHHHHHHHH
      - REACT_APP_NewsApiKey="43c73ae0a1ac456ab319b7a974297975"
