version: "3"

services:
  web:
    build: .
    image: sj2d/watch-tower-1
    ports:
      - "5000:5000"
    environment:
      - mongoURI=mongodb+srv://admin:hXk2se1M1TlLyEfQ@cluster0-9l8kx.mongodb.net/test?retryWrites=true&w=majority
      - secretOrKey="secret SHHHHHHHHHHHHHHHHHHHHHHHHHHH"
      - NewsApiKey=43c73ae0a1ac456ab319b7a974297975 
      - REACT_APP_AV_API_KEY=4TC2D11DD9C6MYST